<a href="https://colab.research.google.com/github/wkdthf21/Machine-Learning-Assignment/blob/master/assignment_03_a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulate PyTorch Tensors
<hr>

## Matrix manipulation

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [4]:

# write your code here

A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[10, 20], [30, 40]])
C = torch.add(A, B)


# print
print(A)
print('')
print(B)
print('')
print(C)

tensor([[1, 2],
        [3, 4]])

tensor([[10, 20],
        [30, 40]])

tensor([[11, 22],
        [33, 44]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [20]:

# write your code here

print(A.dim())    # print the dimension of the matrix A
print('')
print(A.size())    # print the size of the matrix A
print('')
print(A.type())    # print the type of the matrix A

2

torch.Size([2, 2])

torch.LongTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [22]:

# write your code here

A_long = A.long()

print(A_long)    # print the type of A_long
print('')
print(A_long.type())    # print the type of A

tensor([[1, 2],
        [3, 4]])

torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [23]:

# write your code here

A = torch.rand(5, 2, 3)

print(A)
print(A.type())    # print the type of A
print(A.dim())    # print the dimension of A
print(A.size())    # print the size of A
print(A[1].size())    # print the size of the middle (second) dimension

tensor([[[0.0675, 0.2911, 0.8740],
         [0.2870, 0.7351, 0.4896]],

        [[0.4972, 0.3345, 0.6384],
         [0.4494, 0.7999, 0.6875]],

        [[0.6940, 0.7455, 0.2047],
         [0.8472, 0.0257, 0.9212]],

        [[0.7657, 0.8706, 0.5296],
         [0.2669, 0.7012, 0.4710]],

        [[0.1954, 0.8896, 0.0994],
         [0.1199, 0.9856, 0.4272]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
torch.Size([2, 3])


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [24]:

# write your code here

A = torch.zeros(2, 3, 4, 5)

print(A)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
